# This rule is not used by the project controllersync itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over core.tbh.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controllersync
    app.kubernetes.io/managed-by: kustomize
  name: notifier-admin-role
rules:
- apiGroups:
  - core.tbh.dev
  resources:
  - notifiers
  verbs:
  - '*'
- apiGroups:
  - core.tbh.dev
  resources:
  - notifiers/status
  verbs:
  - get
